# Generated by Django 5.2.7 on 2025-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_soldproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
