# Generated by Django 5.2.7 on 2025-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_cost_price_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
