# Generated by Django 5.2.7 on 2025-10-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_soldproduct_sold_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
    ]
