# Generated by Django 5.2.7 on 2025-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_soldproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
