# Generated by Django 5.2.7 on 2025-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_soldproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
